### ISSUE TITLE
Implement Binary Search in C

### ISSUE THREAD

**Issue by PawanKolhe** [PawanKolhe/C-Algorithms#20]
Implement **Binary Search** in C and place it in the '/Searching' folder.

**Comment by Afifibytes** [comment]
Hey @PawanKolhe 
Can I implement this?

**Comment by PawanKolhe** [comment]
Sure @Afifibytes ! Go ahead.

**Comment by Afifibytes** [comment]
@PawanKolhe Done!
https://github.com/PawanKolhe/C-Algorithms/pull/29

**Comment by PawanKolhe** [comment]
Thanks for contributing!
