### ISSUE TITLE
Implement Counting Sort in C 

### ISSUE THREAD

**Issue by PawanKolhe** [PawanKolhe/C-Algorithms#39]
Implement **Counting Sort** in C and place it in the '/Sorting' folder.

**Comment by aman05382** [comment]
Sir, I am interested in this project and also I write the program. But what to do now

**Comment by jadijadi** [comment]
Sorry @aman05382 .. I have sent a PR for this. Sorry for not commenting first, I just wanted to see if I remember the counting sort. 
Dear @PawanKolhe , I've sent a PR for this. Sorry for not asking for permission first. My bad.

**Comment by jadijadi** [comment]
> Sir, I am interested in this project and also I write the program. But what to do now

Dear @aman05382 , you have to fork the project first, then it is good to create a new branch for this issue (using the issue number is a good idea) and when you have done changes and pushed your branch to the github on your forked repo, you can come to this project and there will be a "create new pull request" button (or something like it) on the main page.

**Comment by aman05382** [comment]
ok, but the first message was mine and when I am applying for the previous project at that time owner says that who message first he/she will get assigned.

**Comment by PawanKolhe** [comment]
@jadijadi I'll wait for a day for aman to send pull request. In case he doesn't I'll merge your solution.
Also thanks for guiding others. 👍

**Comment by aman05382** [comment]
> @jadijadi I'll wait for a day for aman to send pull request. In case he doesn't I'll merge your solution.
> Also thanks for guiding others. 👍

thank you sir , for giving me a chance I have done the pull request, I have done this for the first time.
