### ISSUE TITLE
Implement Linear Search in C

### ISSUE THREAD

**Issue by PawanKolhe** [PawanKolhe/C-Algorithms#40]
Implement **Linear Search** in C and place it in the '/Searching' folder.

**Comment by ShubhankarKG** [comment]
please let me handle it

**Comment by aman05382** [comment]
Sir, I am interested in this project and also I write the program. But what to do now

**Comment by PawanKolhe** [comment]
@ShubhankarKG Go ahead.

**Comment by PawanKolhe** [comment]
@aman05382 Shubhankar commented first so I assigned it to him. You can check out other Issues to implement.

**Comment by aman05382** [comment]
ok I don't have any problem but I  applied for another project also, please assign me that project
