### ISSUE TITLE
Implement Exponential Search in C

### ISSUE THREAD

**Issue by PawanKolhe** [PawanKolhe/C-Algorithms#43]
Implement **Exponential Search** in C and place it in the '/Searching' folder.

**Comment by nogarcia** [comment]
As far as my very small amount of algorithm knowledge goes, an exponential search uses a binary search. Should a binary search function be included in the exponential search function or should it be brought in from the existing /Searching/binarySearch.c with `#include`?

**Comment by PawanKolhe** [comment]
@Shrubhog You can include binary search function in the same file.

**Comment by nogarcia** [comment]
Oops, looks like @ye1dos already submitted a PR in #78. 😅 I'll pick up a different one.
